version: '3.10'

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: rahmidin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres3